// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97n2Cken3qPw8dMq68DNnmEI16xWqYXU',
    appId: '1:129060840625:web:7d6957b7d761cbfb92ae90',
    messagingSenderId: '129060840625',
    projectId: 'tubes-ppbm',
    authDomain: 'tubes-ppbm.firebaseapp.com',
    storageBucket: 'tubes-ppbm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRYpl38j9WZC68OZDu0yu7BzgfwoRvIw',
    appId: '1:129060840625:android:612ae10b8aef495c92ae90',
    messagingSenderId: '129060840625',
    projectId: 'tubes-ppbm',
    storageBucket: 'tubes-ppbm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTgY7SCKOchtrN4P0TPCICeXOoYW6RBQ',
    appId: '1:129060840625:ios:fe88c67ee604f4fc92ae90',
    messagingSenderId: '129060840625',
    projectId: 'tubes-ppbm',
    storageBucket: 'tubes-ppbm.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJTgY7SCKOchtrN4P0TPCICeXOoYW6RBQ',
    appId: '1:129060840625:ios:fe88c67ee604f4fc92ae90',
    messagingSenderId: '129060840625',
    projectId: 'tubes-ppbm',
    storageBucket: 'tubes-ppbm.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA97n2Cken3qPw8dMq68DNnmEI16xWqYXU',
    appId: '1:129060840625:web:e88ee19416a8a32a92ae90',
    messagingSenderId: '129060840625',
    projectId: 'tubes-ppbm',
    authDomain: 'tubes-ppbm.firebaseapp.com',
    storageBucket: 'tubes-ppbm.firebasestorage.app',
  );
}
